### ISSUE TITLE
booking-mvc (under stress) : hotel null in bookingsTable.html

### ISSUE THREAD

**Issue by hasalex** [spring-projects/spring-webflow-samples#31]
Hi,

I've deployed the booking-mvc application on Tomcat and I launch stress tests with Gatling. I see randomly (once for 100-200 request) this errors :

```
ERROR: org.thymeleaf.TemplateEngine - [THYMELEAF][http-nio-8082-exec-23] Exception processing template "/hotels/bookingsTable.html": Exception evaluating SpringEL expression: "hotel.city" (/hotels/bookingsTable.html:75)
ERROR: org.thymeleaf.TemplateEngine - [THYMELEAF][http-nio-8082-exec-23] Exception processing template "hotels/search.html": Exception evaluating SpringEL expression: "hotel.city" (/hotels/bookingsTable.html:75)
ERROR: org.thymeleaf.TemplateEngine - [THYMELEAF][http-nio-8082-exec-23] Exception processing template "/layouts/standard.html": Exception evaluating SpringEL expression: "hotel.city" (/hotels/bookingsTable.html:75)
```

In the detailed logs, I have this stacktrace :

`````
GRAVE: Servlet.service() for servlet [dispatcher] in context with path [] threw exception [Request processing failed; nested exception is org.thymeleaf.exceptions.TemplateProcessingException: Exception evaluating SpringEL expression: "hotel.city" (/hotels/bookingsTable.html:75)] with root cause
java.lang.NullPointerException
	at org.springframework.expression.spel.ast.PropertyOrFieldReference.getValueInternal(PropertyOrFieldReference.java:85)
	at org.springframework.expression.spel.ast.CompoundExpression.getValueRef(CompoundExpression.java:51)
	at org.springframework.expression.spel.ast.CompoundExpression.getValueInternal(CompoundExpression.java:87)
	at org.springframework.expression.spel.ast.SpelNodeImpl.getValue(SpelNodeImpl.java:120)
	at org.springframework.expression.spel.standard.SpelExpression.getValue(SpelExpression.java:267)
	at org.thymeleaf.spring4.expression.SpelVariableExpressionEvaluator.evaluate(SpelVariableExpressionEvaluator.java:139)
	at org.thymeleaf.standard.expression.SelectionVariableExpression.executeSelectionVariable(SelectionVariableExpression.java:141)
	at org.thymeleaf.standard.expression.SimpleExpression.executeSimple(SimpleExpression.java:80)
	at org.thymeleaf.standard.expression.Expression.execute(Expression.java:103)
	at ...
````

Data seem correct in database. I don't understand where it comes from.

**Comment by danielfernandez** [comment]
It's a bug in Spring 4.1's SpEL < 4.1.7. See https://jira.spring.io/browse/SPR-13023

**Comment by hasalex** [comment]
Thanks Daniel. I've tried with 4.2.0.RC1. The issue is fixed.

**Comment by rstoyanchev** [comment]
4.1.7 should be available on Monday.
